### ISSUE TITLE
Game logs contain: `Failed to load properties from file: .\config\acrylic.ini`

### ISSUE THREAD

**Issue by 3gf8jv4dv** [DevBobcorn/AcryliCraft#15]
For now, this does not seem to affect the game or mods, but it is confusing.

I am not sure if this is a *bug* or *intended behavior*,  so I am asking here.

*Minecraft `1.21`, NeoForge `21.0.141-beta`, AcryliCraft `1.6.1`, YetAnotherConfigLib `3.5.0`*
<details>
<summary>Details</summary>

```
[net.minecraft.server.dedicated.Settings/]: Failed to load properties from file: .\config\acrylic.ini
java.nio.file.NoSuchFileException: .\config\acrylic.ini
at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234) ~[?:?]
at java.base/java.nio.file.Files.newByteChannel(Files.java:379) ~[?:?]
at java.base/java.nio.file.Files.newByteChannel(Files.java:431) ~[?:?]
at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420) ~[?:?]
at java.base/java.nio.file.Files.newInputStream(Files.java:159) ~[?:?]
at TRANSFORMER/minecraft@1.21/net.minecraft.server.dedicated.Settings.loadFromFile(Settings.java:38) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
at TRANSFORMER/acrylic@1.6.1/io.devbobcorn.acrylic.AcrylicConfig.<init>(AcrylicConfig.java:60) ~[acrylic-neoforge-1.6.1.jar%23184!/:?]
at TRANSFORMER/acrylic@1.6.1/io.devbobcorn.acrylic.AcrylicConfig.getInstance(AcrylicConfig.java:28) ~[acrylic-neoforge-1.6.1.jar%23184!/:?]
at TRANSFORMER/minecraft@1.21/com.mojang.blaze3d.platform.Window.handler$zzc000$acrylic$glfwWindowHintInject(Window.java:589) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
at TRANSFORMER/minecraft@1.21/com.mojang.blaze3d.platform.Window.<init>(Window.java:82) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
at TRANSFORMER/minecraft@1.21/net.minecraft.client.renderer.VirtualScreen.newWindow(VirtualScreen.java:21) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
at TRANSFORMER/minecraft@1.21/net.minecraft.client.Minecraft.<init>(Minecraft.java:467) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
at TRANSFORMER/minecraft@1.21/net.minecraft.client.main.Main.main(Main.java:214) ~[client-1.21-20240613.152323-srg.jar%23182!/:?]
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
at MC-BOOTSTRAP/fml_loader@4.0.19/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.19.jar%23126!/:4.0]
at MC-BOOTSTRAP/fml_loader@4.0.19/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.19.jar%23126!/:4.0]
at MC-BOOTSTRAP/fml_loader@4.0.19/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.19.jar%23126!/:4.0]
at MC-BOOTSTRAP/fml_loader@4.0.19/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.19.jar%23126!/:4.0]
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23101!/:?]
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23101!/:?]
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23101!/:?]
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23101!/:?]
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23101!/:?]
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23101!/:?]
at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23101!/:?]
at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
```

</details>

*Minecraft `1.20.1`, NeoForge `47.1.106`, AcryliCraft `1.4.0`, YetAnotherConfigLib `3.2.2`*

<details>
<summary>Details</summary>

```
[net.minecraft.server.dedicated.Settings/]: Failed to load properties from file: .\config\acrylic.ini
java.nio.file.NoSuchFileException: .\config\acrylic.ini
at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
at java.nio.file.Files.newByteChannel(Files.java:432) ~[?:?]
at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422) ~[?:?]
at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
at net.minecraft.server.dedicated.Settings.m_139839_(Settings.java:36) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?]
at io.devbobcorn.acrylic.AcrylicConfig.<init>(AcrylicConfig.java:62) ~[acrylic-forge-1.4.0+1.20.1.jar%23158!/:?]
at io.devbobcorn.acrylic.AcrylicConfig.getInstance(AcrylicConfig.java:26) ~[acrylic-forge-1.4.0+1.20.1.jar%23158!/:?]
at com.mojang.blaze3d.platform.Window.redirect$zzc000$glfwWindowHintRedirect(Window.java:573) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?]
at com.mojang.blaze3d.platform.Window.<init>(Window.java:79) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?]
at net.minecraft.client.renderer.VirtualScreen.m_110872_(VirtualScreen.java:21) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?]
at net.minecraft.client.Minecraft.<init>(Minecraft.java:440) ~[client-1.20.1-20230612.114412-srg.jar%23160!/:?]
at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1%20Neo.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?]
at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.2.2.jar:47.2]
at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.2.2.jar:47.2]
at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.2.2.jar:47.2]
at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.2.2.jar:47.2]
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
```

</details>

*Minecraft `1.21`, Fabric Loader `0.16.0`, Fabric API `0.100.7`, AcryliCraft `1.6.1`, YetAnotherConfigLib `3.5.0`*
<details>
<summary>Details</summary>

```
Failed to load properties from file: .\config\acrylic.ini
java.nio.file.NoSuchFileException: .\config\acrylic.ini
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:234) ~[?:?]
	at java.base/java.nio.file.Files.newByteChannel(Files.java:379) ~[?:?]
	at java.base/java.nio.file.Files.newByteChannel(Files.java:431) ~[?:?]
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420) ~[?:?]
	at java.base/java.nio.file.Files.newInputStream(Files.java:159) ~[?:?]
	at net.minecraft.class_3808.method_16727(class_3808.java:62) [client-intermediary.jar:?]
	at io.devbobcorn.acrylic.AcrylicConfig.<init>(AcrylicConfig.java:60) [acrylic-fabric-1.6.1.jar:?]
	at io.devbobcorn.acrylic.AcrylicConfig.getInstance(AcrylicConfig.java:28) [acrylic-fabric-1.6.1.jar:?]
	at net.minecraft.class_1041.handler$zzb000$acrylic$glfwWindowHintInject(class_1041.java:594) [client-intermediary.jar:?]
	at net.minecraft.class_1041.<init>(class_1041.java:87) [client-intermediary.jar:?]
	at net.minecraft.class_3682.method_16038(class_3682.java:21) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:505) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:239) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
```

</details>

*Minecraft `1.20.1`, Fabric Loader `0.16.0`, Fabric API `0.92.2`, AcryliCraft `1.4.0`, YetAnotherConfigLib `3.2.2`*
<details>
<summary>Details</summary>

```
[Render thread/ERROR]: Failed to load properties from file: .\config\acrylic.ini
java.nio.file.NoSuchFileException: .\config\acrylic.ini
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:380) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:432) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422) ~[?:?]
	at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
	at net.minecraft.class_3808.method_16727(class_3808.java:62) ~[client-intermediary.jar:?]
	at io.devbobcorn.acrylic.AcrylicConfig.<init>(AcrylicConfig.java:62) ~[acrylic-fabric-1.4.0+1.20.1.jar:?]
	at io.devbobcorn.acrylic.AcrylicConfig.getInstance(AcrylicConfig.java:26) ~[acrylic-fabric-1.4.0+1.20.1.jar:?]
	at net.minecraft.class_1041.redirect$zzb000$acrylic$glfwWindowHintRedirect(class_1041.java:579) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.<init>(class_1041.java:85) ~[client-intermediary.jar:?]
	at net.minecraft.class_3682.method_16038(class_3682.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:486) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[1.20.1%20Fabric.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.0.jar:?]
```

</details>

**Comment by DevBobcorn** [comment]
This exception is printed by setting file loader from the base game, it simply means the config file cannot be found and instead default config will be used. Once you change any option in mod settings, a config file will be created and this error will never show up again.
